# Generated by protox. DO NOT EDIT!
# source: ping_service.proto
import abc
import typing

import grpclib.client
import grpclib.const
import grpclib.server

import protobuf_out.ping_service_pb as \
    ping_service_pb


class MyServiceBase(abc.ABC):
    @abc.abstractmethod
    async def ping(self, stream: grpclib.server.Stream):
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/MyService/Ping': grpclib.const.Handler(
                self.ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                ping_service_pb.PingRequest,
                ping_service_pb.PingResponse,
            ),
        }


class MyServiceStub:
    def __init__(self, channel: grpclib.client.Channel):
        self.ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/MyService/Ping',
            ping_service_pb.PingRequest,
            ping_service_pb.PingResponse,
        )
